language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules'
env:
  global:
    - NODE_ENV=test
before_script:
  - psql -c 'create database haventest;' -U postgres
services:
  - postgresql
after_script:
  - npm run coverage
