swagger: "2.0"
info:
  description: "Authors Haven - A Social platform for the creative at heart."
  version: "1.0.0"
  title: "Authors Haven"
basePath: /api/v1/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    put:
      tags:
        - Users
      summary: Update user profile
      operationId: updateUserProfile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that needs to be added to the app
          required: true
          schema:
            $ref: '#/definitions/UpdateProfile'
      responses:
        '200':
          description: User Successfully Updated
        '400':
          description: Error message
  /users/signup:
    post:
      tags:
        - Users
      summary: Add a new user account
      operationId: addUser
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that needs to be added to the app
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        '201':
          description: User Registration successful
  /users/login:
    post:
      tags:
        - Users
      summary: log in registered user
      operationId: login user
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        type: string
      responses:
        '200':
          description: User Login in successful
  /users/reset-password:
    post:
      tags:
        - Users
      summary: Reset password
      operationId: reset password
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Email needed for password reset
          required: true
          schema:
            $ref: '#/definitions/ResetPassword'
      responses:
        '200':
          description: Password reset successful. Check your email for password reset link!
  /users/change-password:
    put:
      tags:
        - Users
      summary: Change password 
      operationId: change password
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
      - name: resetToken
        in: query
        description: reset token
        required: true
        type: string
      - name: body
        in: body
        description: Email needed for password reset
        required: true
        schema:
          $ref: '#/definitions/ChangePassword'
      responses:
        '200':
          description: Password has successfully been changed.
  /articles:
    post:
      tags:
        - Articles
      summary: create a new article
      operationId: addArticles
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: A new article created by a user
          required: true
          schema:
            $ref: '#/definitions/NewArticle'
      responses:
        '201':
          description: Article created successfully
  /profiles/{username}:
    get:
      tags:
        - "Profile"
      summary: Get user profile
      description: "Gets spqcific user profile info"
      operationId: getUserProfileByUsername
      produces:
        - application/json
      parameters:
        - name: "username"
          in: "path"
          description: "ID of user to return"
          required: true
          type: "string"
      responses:
        200:
          description: "Profile displayed successfully"
          schema:
            $ref: "#/definitions/getUserProfile"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
definitions:
  NewUser:
    type: object
    required:
      - firstName
      - lastName
      - email
      - password
      - username
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    xml:
      name: NewUser
  NewArticle:
    type: object
    required:
      - title
      - description
      - body
      - images
    properties:
      title:
        type: string
      body:
        type: string
      description:
        type: string
      images:
        type: string
    xml:
      name: NewArticle
  UpdateProfile:
    type: object
    required:
      - firstName
      - lastName
      - bio
      - image
      - username
    properties:
      firstName:
        type: string
      lastName:
        type: string
      bio:
        type: string
      image:
        type: string
        format: binary
      username:
        type: string
    xml:
      name: UpdateProfile
  ResetPassword:
    type: object
    required:
      - email
    properties:
      email: 
        type: string
    xml:
      name: resetPassword
  ChangePassword:
    type: object
    required:
      - password
    properties:
      password: 
        type: string
    xml:
      name: changePassword
  getUserProfile:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      email:
        type: "string"
        format: "email"
        example: "user@gmail.com"
      username:
        type: "string"
        example: "Vinay"
      bio:
        type: "string"
        description: "User bio"
      firtName:
        type: "string"
        example: "Larry"
      lastName:
        type: "string"
        example: "Baston"
      image:
        type: "string"
        example: "//temp/up.jpg"
      createdAt:
        type: "string"
        format: "date-time"
        example: "2019-07-05T12:23:45.130Z"
      updatedAt:
        type: "string"
        format: "date-time"
        example: "2019-07-05T12:23:45.130Z"      
    xml:
      name: "getUserProfile"
