swagger: "2.0"
info:
  description: "Authors Haven - A Social platform for the creative at heart."
  version: "1.0.0"
  title: "Authors Haven"
basePath: /api/v1/
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/signup:
    post:
      tags:
        - Users
      summary: Add a new user account
      operationId: addUser
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that needs to be added to the app
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        '201':
          description: User Registration successful
  /users/login:
    post:
      tags:
        - Users
      summary: log in registered user
      operationId: login user
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        type: string
      responses:
        '200':
          description: User Login in successful
definitions:
  NewUser:
    type: object
    required:
      - firstName
      - lastName
      - email
      - password
      - username
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    xml:
      name: NewUser